2025-08-24 18:08:31,207 : INFO : root : Loading config.
2025-08-24 18:08:31,211 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-08-24 18:08:31,211 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\cfa6ecba65704a931c9dd214c44986c8.mpf_cache
2025-08-24 18:08:31,335 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\f98ffc0ff5962effface7d86bc406d5c.mpf_cache
2025-08-24 18:08:31,336 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\91cc4d1c993c58dc354e34974b9cfeac.mpf_cache
2025-08-24 18:08:31,336 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\f98ffc0ff5962effface7d86bc406d5c.mpf_cache
2025-08-24 18:08:31,337 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\76792f1d686f89709887dba7bd69667a.mpf_cache
2025-08-24 18:08:31,346 : INFO : ConfigProcessor : Loading config from file C:\Users\White\Documents\Top_Gun_Pinball\modes\bumpers\config\bumpers.yaml.
2025-08-24 18:08:31,358 : INFO : ConfigProcessor : Loading config: C:\Users\White\Documents\Top_Gun_Pinball\modes\bumpers\config\bumpers.yaml
2025-08-24 18:08:31,359 : INFO : ConfigProcessor : Config file cache created: C:\Users\White\AppData\Local\Temp\142bbae4707335cc8e3efaa4364c4893.mpf_cache
2025-08-24 18:08:31,360 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev9
2025-08-24 18:08:31,361 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-08-24-18-08-31-mpf-TopGunPinball.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'full_logfile_path': 'C:\\Users\\White\\Documents\\Top_Gun_Pinball\\logs\\2025-08-24-18-08-31-mpf-TopGunPinball.log'}
2025-08-24 18:08:31,361 : INFO : Machine : MPF path: C:\Users\White\mpf\Lib\site-packages\mpf
2025-08-24 18:08:31,361 : INFO : Machine : Machine path: C:\Users\White\Documents\Top_Gun_Pinball
2025-08-24 18:08:31,361 : INFO : Machine : Platform: win32
2025-08-24 18:08:31,361 : INFO : Machine : Python executable location: C:\Users\White\mpf\Scripts\python.exe
2025-08-24 18:08:31,361 : INFO : Machine : Python version: 3.12.7 (64-bit)
2025-08-24 18:08:31,363 : INFO : Machine : Initializing MPF...
2025-08-24 18:08:31,502 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-08-24 18:08:31,530 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-08-24 18:08:31,530 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev9', 'prev_value': None, 'change': True}
2025-08-24 18:08:31,531 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev9, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-08-24 18:08:31,531 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.12.7', 'prev_value': None, 'change': True}
2025-08-24 18:08:31,691 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-11-10.0.26100-SP0', 'prev_value': None, 'change': True}
2025-08-24 18:08:31,691 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-08-24 18:08:31,691 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '11', 'prev_value': None, 'change': True}
2025-08-24 18:08:31,691 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.26100', 'prev_value': None, 'change': True}
2025-08-24 18:08:31,691 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-08-24 18:08:31,692 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': 'C:\\Users\\White\\Documents\\Top_Gun_Pinball\\logs\\2025-08-24-18-08-31-mpf-TopGunPinball.log', 'prev_value': None, 'change': True}
2025-08-24 18:08:31,692 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-08-24 18:08:31,700 : ERROR : ConfigValidator : Your config contains a value for the setting "mode:shots", but this is not a valid setting name.
2025-08-24 18:08:31,700 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...tting name.')>) at C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py:124
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...tting name.')>) at C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py:124>
Traceback (most recent call last):
  File "C:\Users\White\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py", line 127, in _async_handler_done
    future.result()
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\mode_controller.py", line 119, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
                               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\mode_controller.py", line 152, in _load_mode
    config['mode'] = self.machine.config_validator.validate_config("mode", config['mode'])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_validator.py", line 345, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Your config contains a value for the setting "mode:shots", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://missionpinball.org/logs)
2025-08-24 18:08:31,765 : INFO : Machine : Starting the main run loop with active modes: []
2025-08-24 18:08:31,765 : WARNING : Machine : Attract mode is not active, game will not be playable. Please check your attract mode configuration.
2025-08-24 18:08:31,765 : INFO : Machine : Shutting down...
2025-08-24 18:08:31,765 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-08-24 18:08:32,781 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\machine.py", line 808, in _run_loop
    raise self._exception['exception']
  File "C:\Users\White\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py", line 127, in _async_handler_done
    future.result()
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\mode_controller.py", line 119, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
                               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\mode_controller.py", line 152, in _load_mode
    config['mode'] = self.machine.config_validator.validate_config("mode", config['mode'])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_validator.py", line 345, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Your config contains a value for the setting "mode:shots", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://missionpinball.org/logs)
2025-08-24 18:08:32,804 : INFO : root : MPF run loop ended.
