2025-09-18 12:30:47,534 : INFO : root : Loading config.
2025-09-18 12:30:47,539 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-09-18 12:30:47,539 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\cfa6ecba65704a931c9dd214c44986c8.mpf_cache
2025-09-18 12:30:47,644 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\f98ffc0ff5962effface7d86bc406d5c.mpf_cache
2025-09-18 12:30:47,644 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\91cc4d1c993c58dc354e34974b9cfeac.mpf_cache
2025-09-18 12:30:47,645 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\f98ffc0ff5962effface7d86bc406d5c.mpf_cache
2025-09-18 12:30:47,645 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\76792f1d686f89709887dba7bd69667a.mpf_cache
2025-09-18 12:30:47,646 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\142bbae4707335cc8e3efaa4364c4893.mpf_cache
2025-09-18 12:30:47,646 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\b4249e7b8f95e82c549b9263ef475a09.mpf_cache
2025-09-18 12:30:47,647 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\434e0238e97461d536537fa1d2ac13b8.mpf_cache
2025-09-18 12:30:47,647 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\5cb8a848aaedecad105d66ca86abc153.mpf_cache
2025-09-18 12:30:47,647 : INFO : ConfigProcessor : Loading config from file C:\Users\White\Documents\Top_Gun_Pinball\shows\.\spiral_circle.yaml.
2025-09-18 12:30:47,708 : INFO : ConfigProcessor : Loading config: C:\Users\White\Documents\Top_Gun_Pinball\shows\.\spiral_circle.yaml
2025-09-18 12:30:47,711 : INFO : ConfigProcessor : Config file cache created: C:\Users\White\AppData\Local\Temp\8de5cc7bb4cd85234067138a393db5f5.mpf_cache
2025-09-18 12:30:47,711 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev9
2025-09-18 12:30:47,711 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-09-18-12-30-47-mpf-TopGunPinball.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'full_logfile_path': 'C:\\Users\\White\\Documents\\Top_Gun_Pinball\\logs\\2025-09-18-12-30-47-mpf-TopGunPinball.log'}
2025-09-18 12:30:47,712 : INFO : Machine : MPF path: C:\Users\White\mpf\Lib\site-packages\mpf
2025-09-18 12:30:47,712 : INFO : Machine : Machine path: C:\Users\White\Documents\Top_Gun_Pinball
2025-09-18 12:30:47,712 : INFO : Machine : Platform: win32
2025-09-18 12:30:47,712 : INFO : Machine : Python executable location: C:\Users\White\mpf\Scripts\python.exe
2025-09-18 12:30:47,712 : INFO : Machine : Python version: 3.12.7 (64-bit)
2025-09-18 12:30:47,714 : INFO : Machine : Initializing MPF...
2025-09-18 12:30:47,849 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-09-18 12:30:47,878 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-09-18 12:30:47,878 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 61000, 'prev_value': None, 'change': True}
2025-09-18 12:30:47,878 : INFO : EventManager : Event: ======'machine_var_player2_score'====== Args={'value': 73000, 'prev_value': None, 'change': True}
2025-09-18 12:30:47,878 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev9', 'prev_value': None, 'change': True}
2025-09-18 12:30:47,878 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev9, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-09-18 12:30:47,879 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.12.7', 'prev_value': None, 'change': True}
2025-09-18 12:30:48,039 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-11-10.0.26100-SP0', 'prev_value': None, 'change': True}
2025-09-18 12:30:48,039 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-09-18 12:30:48,039 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '11', 'prev_value': None, 'change': True}
2025-09-18 12:30:48,039 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.26100', 'prev_value': None, 'change': True}
2025-09-18 12:30:48,039 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-09-18 12:30:48,039 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': 'C:\\Users\\White\\Documents\\Top_Gun_Pinball\\logs\\2025-09-18-12-30-47-mpf-TopGunPinball.log', 'prev_value': None, 'change': True}
2025-09-18 12:30:48,039 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-09-18 12:30:48,102 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-09-18 12:30:48,102 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-0', <Platform.Virtual>) <switch.s_trough_1>
2025-09-18 12:30:48,102 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-1', <Platform.Virtual>) <switch.s_trough_2>
2025-09-18 12:30:48,102 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-2', <Platform.Virtual>) <switch.s_trough_3>
2025-09-18 12:30:48,102 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-3', <Platform.Virtual>) <switch.s_trough_4>
2025-09-18 12:30:48,102 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-4', <Platform.Virtual>) <switch.s_trough_5>
2025-09-18 12:30:48,102 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-5', <Platform.Virtual>) <switch.s_trough_6>
2025-09-18 12:30:48,104 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2025-09-18 12:30:48,108 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2025-09-18 12:30:48,119 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2025-09-18 12:30:48,119 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2025-09-18 12:30:48,120 : INFO : ball_device.bd_plunger : BCH: Initial count: 0
2025-09-18 12:30:48,120 : INFO : ball_device.bd_plunger : State: idle
2025-09-18 12:30:48,120 : INFO : ball_device.bd_trough : BCH: Initial count: 6
2025-09-18 12:30:48,121 : INFO : ball_device.bd_trough : State: idle
2025-09-18 12:30:48,121 : INFO : ball_device.bd_lock_elevator : BCH: Initial count: 0
2025-09-18 12:30:48,121 : INFO : ball_device.bd_lock_elevator : State: idle
2025-09-18 12:30:48,122 : INFO : ball_device.bd_mode_scoop : BCH: Initial count: 0
2025-09-18 12:30:48,122 : INFO : ball_device.bd_mode_scoop : State: idle
2025-09-18 12:30:48,138 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2025-09-18 12:30:48,162 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe... l_gi_light')>)
handle: <Handle EventManager._queue_task_done(<Task finishe... l_gi_light')>)>
Traceback (most recent call last):
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 122, in _convert_color
    color = RGBColor(color)
            ^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\rgb_color.py", line 177, in __init__
    self._color = RGBColor.string_to_rgb(color)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\rgb_color.py", line 420, in string_to_rgb
    raise ColorException("Invalid RGB string: {}".format(value))
mpf.core.rgb_color.ColorException: Invalid RGB string: l_gi_light

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\White\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\assets\show.py", line 201, in _process_step_actions
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\assets\show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 83, in _validate_config_item
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 80, in _validate_config_item
    device_settings = self._expand_device_config(device_settings)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 133, in _expand_device_config
    device_settings['color'] = self._convert_color(color)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 124, in _convert_color
    self.raise_config_error("Invalid color {}".format(color), 1, source_exception=e, context=context)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\logging.py", line 175, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in light_player: Show "spiral_circle" >> Failed to load config player spiral_circle:lights with settings {'l_eject': 'red', 'l_shoot_again': 'red', 'l_goose_g': 'red', 'l_goose_o_left': 'red', 'l_goose_o_right': 'red', 'l_goose_s': 'red', 'l_goose_e': 'red', 'l_mig_m': 'red', 'l_mig_i': 'red', 'l_mig_g': 'red', 'l_iceman_i': 'red', 'l_iceman_c': 'red', 'l_iceman_e': 'red', 'l_iceman_m': 'red', 'l_iceman_a': 'red', 'l_iceman_n': 'red', 'l_lock_l': 'red', 'l_lock_o': 'red', 'l_lock_c': 'red', 'l_lock_k': 'red', 'l_lock_lit': 'red', 'l_lock_mav': 'red', 'l_lock_goose': 'red', 'l_mode_rescue_cougar': 'red', 'l_mode_balls_of_fire': 'red', 'l_mode_cool_under_pressure': 'red', 'l_mode_battle_jester': 'red', 'l_mode_no_points_for_second_place': 'red', 'l_mode_edge_of_space': 'red', 'l_mode_below_the_hard_deck': 'red', 'l_mode_canyon_run': 'red', 'l_mode_rise_of_phoenix': 'red', 'l_mode_no_margin_for_error': 'red', 'l_mode_inverted': 'red', 'l_mode_missles': 'red', 'l_mode_afterburner': 'red', 'l_mode_wingman': 'red', 'l_mode_dogfight': 'red', 'l_mode_top_top_gun': 'red', 'l_mode_gun_top_gun': 'red', 'l_shot_left_lane': 'red', 'l_shot_left_orbit': 'red', 'l_shot_left_ramp': 'red', 'l_shot_spinner': 'red', 'l_shot_barrier': 'red', 'l_shot_tower_ramp': 'red', 'l_shot_upper_orbit': 'red', 'l_shot_middle_ramp': 'red', 'l_shot_right_orbit': 'red', 'l_shot_pilot_gear': 'red', 'l_gi_light_1': 'red', 'l_gi_light_2': 'red', 'l_gi_light_3': 'red', 'l_gi_light_4': 'red', 'l_gi_light': None} >> Failed to expand entry "l_gi_light". >> Invalid color l_gi_light Error Code: CFE-light_player-1 (https://missionpinball.org/logs)
2025-09-18 12:30:48,281 : INFO : Machine : Starting the main run loop with active modes: []
2025-09-18 12:30:48,281 : WARNING : Machine : Attract mode is not active, game will not be playable. Please check your attract mode configuration.
2025-09-18 12:30:48,281 : INFO : Machine : Shutting down...
2025-09-18 12:30:48,282 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-09-18 12:30:49,292 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 122, in _convert_color
    color = RGBColor(color)
            ^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\rgb_color.py", line 177, in __init__
    self._color = RGBColor.string_to_rgb(color)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\rgb_color.py", line 420, in string_to_rgb
    raise ColorException("Invalid RGB string: {}".format(value))
mpf.core.rgb_color.ColorException: Invalid RGB string: l_gi_light

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\machine.py", line 808, in _run_loop
    raise self._exception['exception']
  File "C:\Users\White\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\assets\show.py", line 201, in _process_step_actions
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\assets\show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 83, in _validate_config_item
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 80, in _validate_config_item
    device_settings = self._expand_device_config(device_settings)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 133, in _expand_device_config
    device_settings['color'] = self._convert_color(color)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 124, in _convert_color
    self.raise_config_error("Invalid color {}".format(color), 1, source_exception=e, context=context)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\logging.py", line 175, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in light_player: Show "spiral_circle" >> Failed to load config player spiral_circle:lights with settings {'l_eject': 'red', 'l_shoot_again': 'red', 'l_goose_g': 'red', 'l_goose_o_left': 'red', 'l_goose_o_right': 'red', 'l_goose_s': 'red', 'l_goose_e': 'red', 'l_mig_m': 'red', 'l_mig_i': 'red', 'l_mig_g': 'red', 'l_iceman_i': 'red', 'l_iceman_c': 'red', 'l_iceman_e': 'red', 'l_iceman_m': 'red', 'l_iceman_a': 'red', 'l_iceman_n': 'red', 'l_lock_l': 'red', 'l_lock_o': 'red', 'l_lock_c': 'red', 'l_lock_k': 'red', 'l_lock_lit': 'red', 'l_lock_mav': 'red', 'l_lock_goose': 'red', 'l_mode_rescue_cougar': 'red', 'l_mode_balls_of_fire': 'red', 'l_mode_cool_under_pressure': 'red', 'l_mode_battle_jester': 'red', 'l_mode_no_points_for_second_place': 'red', 'l_mode_edge_of_space': 'red', 'l_mode_below_the_hard_deck': 'red', 'l_mode_canyon_run': 'red', 'l_mode_rise_of_phoenix': 'red', 'l_mode_no_margin_for_error': 'red', 'l_mode_inverted': 'red', 'l_mode_missles': 'red', 'l_mode_afterburner': 'red', 'l_mode_wingman': 'red', 'l_mode_dogfight': 'red', 'l_mode_top_top_gun': 'red', 'l_mode_gun_top_gun': 'red', 'l_shot_left_lane': 'red', 'l_shot_left_orbit': 'red', 'l_shot_left_ramp': 'red', 'l_shot_spinner': 'red', 'l_shot_barrier': 'red', 'l_shot_tower_ramp': 'red', 'l_shot_upper_orbit': 'red', 'l_shot_middle_ramp': 'red', 'l_shot_right_orbit': 'red', 'l_shot_pilot_gear': 'red', 'l_gi_light_1': 'red', 'l_gi_light_2': 'red', 'l_gi_light_3': 'red', 'l_gi_light_4': 'red', 'l_gi_light': None} >> Failed to expand entry "l_gi_light". >> Invalid color l_gi_light Error Code: CFE-light_player-1 (https://missionpinball.org/logs)
2025-09-18 12:30:49,313 : INFO : root : MPF run loop ended.
