2025-10-29 16:02:25,957 : INFO : root : Loading config.
2025-10-29 16:02:25,971 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-10-29 16:02:25,972 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\4d2409115979d2066280cf8a522910f3.mpf_cache
2025-10-29 16:02:26,101 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\e29f700f4dd412c341ced84fe54a834e.mpf_cache
2025-10-29 16:02:26,103 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\91cc4d1c993c58dc354e34974b9cfeac.mpf_cache
2025-10-29 16:02:26,113 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\e29f700f4dd412c341ced84fe54a834e.mpf_cache
2025-10-29 16:02:26,113 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\3424101e418333c494b4f7abb38a6bbc.mpf_cache
2025-10-29 16:02:26,115 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\928267ba5ce09cfb7bef110abe29482e.mpf_cache
2025-10-29 16:02:26,116 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\fcd858616785c392a2718eef83d6bdec.mpf_cache
2025-10-29 16:02:26,128 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\cbf9c95ed33e797787d40a3c26fb1f29.mpf_cache
2025-10-29 16:02:26,130 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\0f477732e86fa3539be0c16808cbc3a4.mpf_cache
2025-10-29 16:02:26,142 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\White\documents\Top_Gun_Pinball\shows\.\attract_chase_all_inserts.yaml
2025-10-29 16:02:26,142 : INFO : ConfigProcessor : Loading config from file C:\Users\White\documents\Top_Gun_Pinball\shows\.\attract_chase_all_inserts.yaml.
2025-10-29 16:02:26,429 : INFO : ConfigProcessor : Loading config: C:\Users\White\documents\Top_Gun_Pinball\shows\.\attract_chase_all_inserts.yaml
2025-10-29 16:02:26,432 : INFO : ConfigProcessor : Config file cache created: C:\Users\White\AppData\Local\Temp\5252be9889d0ea92e9251ccb139bb96e.mpf_cache
2025-10-29 16:02:26,433 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\bbd12103fd66360c81da95fa3b5d5cac.mpf_cache
2025-10-29 16:02:26,451 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\aecbb0084a39aaddc8e1af6d86d05e57.mpf_cache
2025-10-29 16:02:26,464 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\a64c515fc9f6d1ba4d043d8acedc61d8.mpf_cache
2025-10-29 16:02:26,477 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\157e473ad106aaf7621d4ff67f908349.mpf_cache
2025-10-29 16:02:26,492 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\b42daedb456e388e83b54e0791e694a7.mpf_cache
2025-10-29 16:02:26,503 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\faf1d2b55b8b754be547ffd9950d5977.mpf_cache
2025-10-29 16:02:26,515 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\881befc175503515b6a677d4b92fd8f6.mpf_cache
2025-10-29 16:02:26,532 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\e02fdb456b236b981c3cd16c62d08cdd.mpf_cache
2025-10-29 16:02:26,547 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\60f49b772835308c8a63a813f3984bd2.mpf_cache
2025-10-29 16:02:26,561 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\b44eabe64ef7d1af51d3871ffce6e8a0.mpf_cache
2025-10-29 16:02:26,563 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\806e2c11867b05313045539710e5cf3e.mpf_cache
2025-10-29 16:02:26,565 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\d4cc51f9996852dab0efd4baeb323b9c.mpf_cache
2025-10-29 16:02:26,567 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev9
2025-10-29 16:02:26,567 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-10-29-16-02-25-mpf-TopGunPinball.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'full_logfile_path': 'C:\\Users\\White\\documents\\Top_Gun_Pinball\\logs\\2025-10-29-16-02-25-mpf-TopGunPinball.log'}
2025-10-29 16:02:26,567 : INFO : Machine : MPF path: C:\Users\White\mpf\Lib\site-packages\mpf
2025-10-29 16:02:26,567 : INFO : Machine : Machine path: C:\Users\White\documents\Top_Gun_Pinball
2025-10-29 16:02:26,567 : INFO : Machine : Platform: win32
2025-10-29 16:02:26,567 : INFO : Machine : Python executable location: C:\Users\White\mpf\Scripts\python.exe
2025-10-29 16:02:26,567 : INFO : Machine : Python version: 3.12.7 (64-bit)
2025-10-29 16:02:26,570 : INFO : Machine : Initializing MPF...
2025-10-29 16:02:26,705 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-10-29 16:02:26,734 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-10-29 16:02:26,734 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 2229000, 'prev_value': None, 'change': True}
2025-10-29 16:02:26,734 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev9', 'prev_value': None, 'change': True}
2025-10-29 16:02:26,734 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev9, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-10-29 16:02:26,734 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.12.7', 'prev_value': None, 'change': True}
2025-10-29 16:02:26,893 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-11-10.0.26100-SP0', 'prev_value': None, 'change': True}
2025-10-29 16:02:26,893 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-10-29 16:02:26,893 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '11', 'prev_value': None, 'change': True}
2025-10-29 16:02:26,893 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.26100', 'prev_value': None, 'change': True}
2025-10-29 16:02:26,894 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-10-29 16:02:26,894 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': 'C:\\Users\\White\\documents\\Top_Gun_Pinball\\logs\\2025-10-29-16-02-25-mpf-TopGunPinball.log', 'prev_value': None, 'change': True}
2025-10-29 16:02:26,894 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-10-29 16:02:26,941 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-10-29 16:02:26,942 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-0', <Platform.Virtual>) <switch.s_trough_1>
2025-10-29 16:02:26,942 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-1', <Platform.Virtual>) <switch.s_trough_2>
2025-10-29 16:02:26,942 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-2', <Platform.Virtual>) <switch.s_trough_3>
2025-10-29 16:02:26,942 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-3', <Platform.Virtual>) <switch.s_trough_4>
2025-10-29 16:02:26,942 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-4', <Platform.Virtual>) <switch.s_trough_5>
2025-10-29 16:02:26,942 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-5', <Platform.Virtual>) <switch.s_trough_6>
2025-10-29 16:02:26,966 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2025-10-29 16:02:26,968 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2025-10-29 16:02:26,982 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2025-10-29 16:02:26,982 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2025-10-29 16:02:26,983 : INFO : ball_device.bd_plunger : BCH: Initial count: 0
2025-10-29 16:02:26,983 : INFO : ball_device.bd_plunger : State: idle
2025-10-29 16:02:26,983 : INFO : ball_device.bd_trough : BCH: Initial count: 6
2025-10-29 16:02:26,983 : INFO : ball_device.bd_trough : State: idle
2025-10-29 16:02:26,983 : INFO : ball_device.bd_lock_elevator : BCH: Initial count: 0
2025-10-29 16:02:26,984 : INFO : ball_device.bd_lock_elevator : State: idle
2025-10-29 16:02:26,984 : INFO : ball_device.bd_mode_scoop : BCH: Initial count: 0
2025-10-29 16:02:26,984 : INFO : ball_device.bd_mode_scoop : State: idle
2025-10-29 16:02:26,999 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2025-10-29 16:02:27,003 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...color 80808')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...color 80808')>)>
Traceback (most recent call last):
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 122, in _convert_color
    color = RGBColor(color)
            ^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\rgb_color.py", line 177, in __init__
    self._color = RGBColor.string_to_rgb(color)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\rgb_color.py", line 420, in string_to_rgb
    raise ColorException("Invalid RGB string: {}".format(value))
mpf.core.rgb_color.ColorException: Invalid RGB string: 80808

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\White\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\assets\show.py", line 201, in _process_step_actions
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\assets\show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 83, in _validate_config_item
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 80, in _validate_config_item
    device_settings = self._expand_device_config(device_settings)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 133, in _expand_device_config
    device_settings['color'] = self._convert_color(color)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 124, in _convert_color
    self.raise_config_error("Invalid color {}".format(color), 1, source_exception=e, context=context)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\logging.py", line 175, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in light_player: Show "attract_chase_all_inserts" >> Failed to load config player attract_chase_all_inserts:lights with settings {'l_gi_light_1': 80808, 'l_gi_light_10': 80808, 'l_gi_light_11': 80808, 'l_gi_light_12': 80808, 'l_gi_light_13': 80808, 'l_gi_light_14': 80808, 'l_gi_light_15': 80808, 'l_gi_light_16': 80808, 'l_gi_light_17': 80808, 'l_gi_light_18': 80808, 'l_gi_light_19': 80808, 'l_gi_light_2': 80808, 'l_gi_light_20': 80808, 'l_gi_light_21': 80808, 'l_gi_light_3': 80808, 'l_gi_light_4': 80808, 'l_gi_light_5': 80808, 'l_gi_light_6': 80808, 'l_gi_light_7': 80808, 'l_gi_light_8': 80808, 'l_gi_light_9': 80808, 'l_goose_g': 666666, 'l_iceman_i': 666666, 'l_iceman_m': 666666, 'l_mig_m': 666666, 'l_mode_edge_of_space': 666666, 'l_mode_inverted': 666666, 'l_mode_rescue_cougar': 666666, 'l_mode_top_top_gun': 666666, 'l_pilot_training_lit': 666666, 'l_shot_left_lane': 666666} >> Failed to expand entry "l_gi_light_1". >> Invalid color 80808 Error Code: CFE-light_player-1 (https://missionpinball.org/logs)
2025-10-29 16:02:27,122 : INFO : Machine : Starting the main run loop with active modes: []
2025-10-29 16:02:27,122 : WARNING : Machine : Attract mode is not active, game will not be playable. Please check your attract mode configuration.
2025-10-29 16:02:27,122 : INFO : Machine : Shutting down...
2025-10-29 16:02:27,122 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-10-29 16:02:28,131 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 122, in _convert_color
    color = RGBColor(color)
            ^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\rgb_color.py", line 177, in __init__
    self._color = RGBColor.string_to_rgb(color)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\rgb_color.py", line 420, in string_to_rgb
    raise ColorException("Invalid RGB string: {}".format(value))
mpf.core.rgb_color.ColorException: Invalid RGB string: 80808

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\machine.py", line 808, in _run_loop
    raise self._exception['exception']
  File "C:\Users\White\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\assets\show.py", line 201, in _process_step_actions
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\assets\show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 83, in _validate_config_item
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 80, in _validate_config_item
    device_settings = self._expand_device_config(device_settings)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 133, in _expand_device_config
    device_settings['color'] = self._convert_color(color)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 124, in _convert_color
    self.raise_config_error("Invalid color {}".format(color), 1, source_exception=e, context=context)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\logging.py", line 175, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in light_player: Show "attract_chase_all_inserts" >> Failed to load config player attract_chase_all_inserts:lights with settings {'l_gi_light_1': 80808, 'l_gi_light_10': 80808, 'l_gi_light_11': 80808, 'l_gi_light_12': 80808, 'l_gi_light_13': 80808, 'l_gi_light_14': 80808, 'l_gi_light_15': 80808, 'l_gi_light_16': 80808, 'l_gi_light_17': 80808, 'l_gi_light_18': 80808, 'l_gi_light_19': 80808, 'l_gi_light_2': 80808, 'l_gi_light_20': 80808, 'l_gi_light_21': 80808, 'l_gi_light_3': 80808, 'l_gi_light_4': 80808, 'l_gi_light_5': 80808, 'l_gi_light_6': 80808, 'l_gi_light_7': 80808, 'l_gi_light_8': 80808, 'l_gi_light_9': 80808, 'l_goose_g': 666666, 'l_iceman_i': 666666, 'l_iceman_m': 666666, 'l_mig_m': 666666, 'l_mode_edge_of_space': 666666, 'l_mode_inverted': 666666, 'l_mode_rescue_cougar': 666666, 'l_mode_top_top_gun': 666666, 'l_pilot_training_lit': 666666, 'l_shot_left_lane': 666666} >> Failed to expand entry "l_gi_light_1". >> Invalid color 80808 Error Code: CFE-light_player-1 (https://missionpinball.org/logs)
2025-10-29 16:02:28,156 : INFO : root : MPF run loop ended.
